# Copy this file to /etc/currentcostd.yml OR ./currentcostd.yml and add your
# own settings.

currentcost:
  port: /dev/ttyS0
  cc128: true

# Enable this to dump meter data to standard output
debug:
  enabled: true

# Enable this to publish to a feed on www.pachube.com
pachube:
  enabled: false
  feed_id: your_pachube_feed_id_goes_here (e.g. 123)
  api_key: your_pachube_api_key_goes_here

# Enable this to run a web server which you can look at in a browser
http:
  enabled: false
  port: 3500

# Enable this section to post data to www.carbondiet.org
carbondiet:
  enabled: false
  username: your_carbondiet_username_goes_here
  password: your_carbondiet_password_goes_here

# Enable this section to send data directly to an AMEE profile
# The profile with the specified UID should already exist.
amee:
  enabled: false
  server: stage.amee.com
  username: your_amee_username_goes_here
  password: your_amee_password_goes_here
  profile_uid: ABC123DEF456

# This publisher submits to a realtime carbon category in AMEE 
# (currently only in testing)
amee_realtime:
  enabled: false
  server: realtime.stage.amee.com
  username: your_amee_username_goes_here
  password: your_amee_password_goes_here
  profile_uid: ABCD123DEF456

# Enable this section to post to Twitter.
# This will post once a minute - I don't suggest you use your normal Twitter account ;)
twitter:
  enabled: false
  username: your_twitter_username_goes_here
  password: your_twitter_password_goes_here
